import uuid
from typing import TYPE_CHECKING

from sqlalchemy import (
    CheckConstraint,
    Enum as SAEnum,
    Float,
    ForeignKey,
    Index,
    String,
    func,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
import enum
from app.core.db import Base

if TYPE_CHECKING:
    from app.models.document import Document


class TagAssignedBy(str, enum.Enum):
    AUTO = "auto"  # generated by the Claude auto-tagging pass
    USER = "user"


def enum_values(enum_cls: type[enum.Enum]) -> list[str]:
    return [member.value for member in enum_cls]


class Tag(Base):
    __tablename__ = "tags"
    __table_args__ = (
        CheckConstraint("color ~ '^#[0-9A-Fa-f]{6}$'", name="ck_tags_color_is_hex"),
    )
    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name: Mapped[str] = mapped_column(String(64))
    color: Mapped[str] = mapped_column(String(7), default="#9CA3AF")
    documents: Mapped[list["DocumentTag"]] = relationship(back_populates="tag", cascade="all, delete-orphan")


# Functional unique index: "Work" and "work" must not become two tags
Index("ix_tags_name_lower", func.lower(Tag.name), unique=True)


class DocumentTag(Base):
    __tablename__ = "document_tags"
    __table_args__ = (
        # confidence belongs to auto-assigned tags only
        CheckConstraint(
            "(assigned_by = 'user' AND confidence IS NULL)"
            " OR (assigned_by = 'auto')",
            name="ck_document_tags_confidence_only_for_auto",
        ),
    )
    document_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("documents.id", ondelete="CASCADE"), primary_key=True)
    tag_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("tags.id", ondelete="CASCADE"), primary_key=True, index=True
    )
    assigned_by: Mapped[TagAssignedBy] = mapped_column(
        SAEnum(TagAssignedBy, name="tag_assigned_by", values_callable=enum_values),
        default=TagAssignedBy.AUTO,
    )
    confidence: Mapped[float | None] = mapped_column(Float)
    document: Mapped["Document"] = relationship(back_populates="tags")
    tag: Mapped["Tag"] = relationship(back_populates="documents")